config/routes.rb
Rails.application.routes.draw do


	root 'staticpages#home'
	get  '/help',    to: 'staticpages#help'
	get  '/about',   to: 'staticpages#about'
  	get  '/signup',  to: 'users#new'

	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users do
	    member do
	      get :following, :followers
	    end
	end
	resources :users
	resources :account_activations, only: [:edit]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :microposts,          only: [:create, :destroy]
	resources :relationships,       only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<!-- <div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4 text-center">
			<h3>IzeeTweet</h3>
			<ul class="list-inine text-center" style="padding-left: 0;">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", root_path %></li>
			</ul> <br> <br>
			<p>Design and Implemented By Gabriel &copy; Web Solutions</p>
		</div>

		<div class="col-xs-12 col-sm-6 col-md-4 text-center">
			<h3>
				<span class="glyphicon glyphicon-map-marker"></span>
				<span class="footer_ppl">Address</span>
			</h3>
			<h3>
				<span class="glyphicon glyphicon-phone"></span>
				<span class="footer_ppl">1234567890</span>
			</h3>
			<h3>
				<span class="glyphicon glyphicon-envelope"></span>
				<span class="footer_ppl">gabriel4amaizu@gmail.com</span>
			</h3>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<h3>About the company</h3>
			<ul class="list-inline">
				<li><a href="">
					<span class="glyphicon glyphicon-phone"></span>
				</a></li>	
				<li><a href="">
					<span class="glyphicon glyphicon-phone"></span>
				</a></li>
				<li><a href="">
					<span class="glyphicon glyphicon-phone"></span>
				</a></li>
			</ul>
		</div>
	</div> -->

	<div class="row">
		<div class="col-xs-12">
			<p>copyright  &copy; of Maduka James</p>
		</div>
	</div>
</footer>	

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse" data-spy="affix" data-offset-top="51">
  <div class="container">
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#">Brand</a> -->
        <%= link_to "Zygone", root_path, class: "navbar-brand"%>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zygone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
  window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
  d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
  _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
  $.src="https://v2.zopim.com/?4i7LC9Vjwkv38LCpzKQpyFiD4d2oEnJ3";z.t=+new Date;$.
  type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
  </script>
  </head>

  <body>
  	<%= render 'layouts/header'%>
    <div class="container-fluid">
     <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    	<%= yield %>
    </div>
    <%= render 'layouts/footer'%>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>